### ISSUE TITLE
Wrong listen configuration / No connection with IPv6

### ISSUE THREAD

**Issue by Stoney49th** [OpenMediaVault-Plugin-Developers/openmediavault-nginx#10]
This is somehow related to #9, but I found this today while getting a pydio instance to work with IPv6.

The default config sting for the "Listen" configuration in nginx currently is "listen PORT;" (with my current configuration), where it should be "listen [::]:PORT ipv6only=off;" if there is any IPv6 connectivity on the system (took that one from the omv-webgui config). This also applies to the SSL port where the "[::]:" is missing.

As a result, a website configured with the plugin is not reachable via IPv6 but the rest of the configuration just works fine, as far as pydio is concerned.

**Comment by nohatssir** [comment]
This is fixed with #12

**Comment by Stoney49th** [comment]
Thanks for all the effort! Highly Appreciated! :)
