### ISSUE TITLE
Nginx Down if removes all index pages and index is connected

### ISSUE THREAD

**Issue by raistlin2912** [OpenMediaVault-Plugin-Developers/openmediavault-nginx#13]
If you removes index.html and index.php but leaves checked index, the plugin leaves this line in nginx configuration and doesn't start: index ;

After this OMV WebUI isn't accesible until edits the file and removes that line.

**Comment by nohatssir** [comment]
Can you try 2efbde64bd003122a79f456bc4da266d849e9ab7?

**Comment by raistlin2912** [comment]
Sorry I dont know how to check it, I have installed within WebUI.

**Comment by nohatssir** [comment]
I've verified the configuration now, and the issue should be fixed when the next version is released. Thanks for the report!
