### ISSUE TITLE
NGINX Error when saving without directory

### ISSUE THREAD

**Issue by lulu9** [OpenMediaVault-Plugin-Developers/openmediavault-nginx#15]
Hi.

I have a question. If you have 2 NGINX server on your network (for example first at 192.168.1.10 and 2nd at 192.168.1.11) you can use one of them to reroute a name based webpage to the second NGINX server. For that you have to put a proxy_pass into the options field. This all works fine.

But for that case you have to leave the directory-field empty in the mask. But if you then safe the config you get an error displayed. Nevertheless the nginx config file will be written.

Is it possible to change the plugin so there will be no failure displayed without anything in the directory field?

Regards lulu

here the forum thread: http://forums.openmediavault.org/index.php/Thread/14161-NGINX-Error-when-saving-without-directory/

**Comment by nohatssir** [comment]
I'm not following you. There's only one directory field and that's a shared folder combo. Which field do you mean? What do you mean with "mask"?

**Comment by lulu9** [comment]
Yes I mean the shared folder combo. But if you leave this blank and save the new setting, you get an error window. But entries in the nginx file in /etc/nginx/sites-available are made.

But if you just want to make a proxy_pass entry you don't need a shared folder so you can leave it blank.

**Comment by nohatssir** [comment]
Since you haven't specified what the error says, I going to assume it's actually the error that occurs when Nginx is restarting. It only says something like 'An error has occured'. If that's the case, it's not something I can fix anyway because it's not really an error.

**Comment by lulu9** [comment]
Yes I meant that. Sorry. But I think you can read my mind... :-)

Ah ok, so if it is not a problem at all I can live with it. Thanks for clarification!
