### ISSUE TITLE
openmediavault-nginx deactivates openmediavault-webgui

### ISSUE THREAD

**Issue by cerces** [OpenMediaVault-Plugin-Developers/openmediavault-nginx#18]
Switching on the openmediavault-nginx service works fine and websites are all served but they all take precedence over the regular openmediavault-webgui even if none have the 'Default' flag set.

**Comment by nohatssir** [comment]
Could you try renaming `/etc/nginx/sites-enabled/openmediavault-nginx` to `/etc/nginx/sites-enabled/zzz-openmediavault-nginx` and see if that helps?

**Comment by cerces** [comment]
I can confirm it solves the issue.

**Comment by nohatssir** [comment]
You can try the latest version from git and see if it works. I've changed the config files names. The upgrade will only remove the old ones and the new ones will be created when you edit your config. :)
