### ISSUE TITLE
Fancy indexing

### ISSUE THREAD

**Issue by jult** [OpenMediaVault-Plugin-Developers/openmediavault-nginx#23]
This plugin sure could use the Fancy Indexing module compiled with it.
The shortening of filenames in nginx' autoindex is ridiculously silly. Who would prefer that over showing the full filenames?

**Comment by nohatssir** [comment]
This won't happen since no one will be compiling and packaging Nginx when it's already packaged in Debian.

**Comment by jult** [comment]
Since debian is far behind on their nginx packaging anyway, why not provide one? You could easily add the deb package provided by nginx, which is already at 1.10.3 now, or use the source for that and recompile with Fancy Indexing included. If you mean to say nobody is willing to do so, OK, I can live with that, but just using the debian provided nginx version is rather outdated anyway. I already use the newer one with OMV, works just fine.
