### ISSUE TITLE
Firewall doesn't allow the "All" Protocol option

### ISSUE THREAD

**Issue by yllekz** [OpenMediaVault-Plugin-Developers/openmediavault-nginx#34]
Hey there, I've noticed what appears to be a bug in the OMV firewall options:

You are never allowed to select "All" in the protocol dropdown, it says it's a disallowed option despite being in a multiple-choice list.

Example rule with Protocol restriction:

![image](https://user-images.githubusercontent.com/28446638/90264890-c9d8c300-de1f-11ea-83a8-bfb8d8dc8d8b.png)

**Comment by subzero79** [comment]
You need to file this issue in core omv. The firewall frontend is not part of omv extras.

**Comment by subzero79** [comment]
You need to file this issue in core omv. The firewall frontend is not part of omv extras.

**Comment by subzero79** [comment]
You need to file this issue in core omv. The firewall frontend is not part of omv extras.

**Comment by subzero79** [comment]
You need to file this issue in core omv. The firewall frontend is not part of omv extras.

**Comment by subzero79** [comment]
You need to file this issue in core omv. The firewall frontend is not part of omv extras.
