### ISSUE TITLE
Ability to use default server ports

### ISSUE THREAD

**Issue by escoand** [OpenMediaVault-Plugin-Developers/openmediavault-nginx#9]
I just wan't to setup a different virtual host on the exact same interface and port.
It's simple - just do not put any listen option into the configuration.
More effort should be done at the frontend.

**Comment by escoand** [comment]
Huh, there seems to be a problem with multiple single files using the same listen option.
I get the error "Address already in use"...

**Comment by escoand** [comment]
Fixed it. You have to use "listen [::]:443 ssl;"

**Comment by nohatssir** [comment]
This issue needs some clarification.

And also: "More effort should be done at the frontend." In which way?

**Comment by escoand** [comment]
I use openmediavault at port 80 and 443. Additionally I wan't to setup owncloud on the same ports but on different host name. The current frontend does not allow to use the same ports.
First I thaught you just have to leave the listen option but that didn't work.
The solution is to set the listen option to the fully equal port definition - in my case [::]:80 and [::]:443.
The mkconf part should be relatively simple but the frontend needs a bit more attention.

**Comment by DipSwitch** [comment]
This configuration is generated bij the owncloud plugin not the nginx plugin. You could use the ngingx plugin, but this hould be fixed in the owncloud plugin if you ask me?

**Comment by escoand** [comment]
Ok, I missed to say that I use owncloud without the plugin. Using the same ports is not possible with at all.

**Comment by nohatssir** [comment]
Fixed with #12
